//! Experimental receiver setup intents. These values never authorize offline invoices.

use super::{FFORReceiverAbortReason, FFORReceiverError};
use crate::ln::types::ChannelId;
use crate::prelude::*;
use bitcoin::secp256k1::PublicKey;
use lightning_ffor::wire::Init;

/// Local policy for a fixed-amount Variant D request. All deadlines are block heights.
/// The engine derives the budget, epoch, channel identities and live funding limits itself.
#[derive(Clone, Debug)]
pub struct FFORReceiverParameters {
	/// Stable application correlation for exact retries. It never chooses the protocol epoch.
	pub local_request_id: [u8; 32],
	/// Exact voucher amounts in millisatoshis, with one through 483 entries.
	pub amounts_msat: Vec<u64>,
	/// Minimum accepted voucher amount in millisatoshis.
	pub minimum_payment_msat: u64,
	/// Last permitted settlement admission height.
	pub settlement_deadline: u32,
	/// Common absolute voucher expiry height.
	pub voucher_expiry: u32,
	/// Proposed base forwarding fee in millisatoshis.
	pub fee_base_msat: u32,
	/// Proposed proportional forwarding fee in millionths.
	pub fee_proportional_millionths: u32,
	/// Local on-chain claim policy, never a value supplied by the peer.
	pub claim_margin_blocks: u32,
	/// Optional witness peer restriction, with one through four distinct keys when present.
	pub witness_peers: Option<Vec<PublicKey>>,
	/// Request uniform hash-chained vouchers.
	pub hash_chain: bool,
}

impl FFORReceiverParameters {
	pub(crate) fn init(&self) -> Result<Init, FFORReceiverError> {
		if self.amounts_msat.is_empty()
			|| self.amounts_msat.len() > 483
			|| self.witness_peers.as_ref().map_or(false, |peers| peers.len() > 4)
		{
			return Err(super::FFORCommitmentError::InvalidVoucherBook.into());
		}
		if let Some(peers) = self.witness_peers.as_ref() {
			if peers.is_empty()
				|| peers.iter().enumerate().any(|(index, peer)| peers[..index].contains(peer))
			{
				return Err(super::FFORCommitmentError::InvalidVoucherBook.into());
			}
		}
		let budget_msat = self
			.amounts_msat
			.iter()
			.try_fold(0u64, |sum, amount| sum.checked_add(*amount))
			.ok_or(super::FFORCommitmentError::InvalidVoucherBook)?;
		Ok(Init {
			budget_msat,
			min_payment_msat: self.minimum_payment_msat,
			settlement_deadline: self.settlement_deadline,
			voucher_expiry: self.voucher_expiry,
			fee_base_msat: self.fee_base_msat,
			fee_proportional_millionths: self.fee_proportional_millionths,
			amounts_msat: self.amounts_msat.clone(),
			witness_peers: self.witness_peers.clone(),
			hash_chain: self.hash_chain,
		})
	}
}

/// An epoch selector returned by native admission. Possessing it grants no phase authority.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FFORReceiverId {
	pub(crate) channel_id: ChannelId,
	pub(crate) epoch_id: [u8; 32],
}

impl FFORReceiverId {
	/// The channel that owns this request.
	pub fn channel_id(&self) -> ChannelId {
		self.channel_id
	}
	/// The fresh epoch generated by the manager.
	pub fn epoch_id(&self) -> [u8; 32] {
		self.epoch_id
	}
}

/// Current native receiver progress. No variant authorizes invoice exposure or witness work.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FFORReceiverProgress {
	/// The ordered manager persister has not yet completed the protected revision.
	AwaitingPersistence,
	/// Exact outgoing bytes remain owned by the engine because the transport queue refused them.
	Backpressured,
	/// Native state awaits an authenticated peer message or the existing stock handshake.
	AwaitingPeer,
	/// Exact accepted vouchers are owned natively and await their stock commitment rounds.
	AwaitingVoucherCommitments,
	/// Obtain an opaque snapshot from the monitor, drop its guard, and use the with-monitor entry.
	NeedsMonitorSnapshot,
	/// The exact signed activation acknowledgement is durable and native frozen state is intact.
	/// This may be observed after the settlement deadline and is not invoice readiness.
	Active,
	/// A durable close acknowledgement owns the stock voucher removal rounds.
	Draining,
	/// Both voucher views are empty and the final Closed manager barrier has completed.
	Closed,
	/// A fresh connection and native reestablish reconciliation are required before more work.
	ReconnectRequired,
	/// Conflicting retained peer evidence requires explicit recovery; the fence is retained.
	ResolutionRequired,
	/// The pending request was irreversibly aborted. The gate remains until controlled release.
	Aborted {
		/// First retained native reason.
		reason: FFORReceiverAbortReason,
	},
}
