[package]
name = "lightning-ffor-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bitcoin = "0.32.7"
lightning-ffor = { path = ".." }

[workspace]
members = ["."]

[[bin]]
name = "wire"
path = "fuzz_targets/wire.rs"
test = false
doc = false
bench = false
